### ISSUE TITLE
Login de Usuário

### ISSUE THREAD

**Issue by PedroFAndrade** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t5-seiton#9]

**Comment by Marcos36523** [comment]
Iniciado o desenvolvimento da tela de Login usando o padrão MVC

**Comment by Marcos36523** [comment]
Tela de Login atualizado com correção de bugs e funcionalidades

**Comment by Marcos36523** [comment]
Iniciando CSS para melhorar o visual

**Comment by Marcos36523** [comment]
Criado layout da tela de login com referência ao template padrão do site.
